// 본문과 메뉴, 검색, 공통 제품 소개 영역을 조합한다.
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { escape, image, icon } from './markdown.mjs';

const THEME_VERSION = JSON.parse(readFileSync(new URL('./vendor/theme/theme.json', import.meta.url))).contentHash;
const SCRIPT_VERSION = createHash('sha256').update(readFileSync(new URL('./site.js', import.meta.url))).digest('hex');
export function search(frequent = false) {
  return `<section class="app-search" data-search role="search" aria-label="Support search"><div class="app-search-field">${image('quickfind-loupe.svg', '', 'app-search-icon')}<label class="app-sr" for="article-search">Search support articles</label><input class="app-search-input" id="article-search" type="text" placeholder="${frequent ? 'Type…' : 'How can we help you?'}" autocomplete="off"><button class="app-search-clear" data-clear type="button" aria-label="Clear search" hidden>${image('quickfind-clear.svg')}</button></div><div class="app-search-results" data-results role="status" aria-live="polite" hidden></div>${frequent ? '<div class="app-search-frequent">Frequent questions: <button data-query="ai tools">ai tools</button> <button data-query="new device">new device</button> <button data-query="discounts">discounts</button> <button data-query="android">android</button></div>' : ''}</section>`;
}
const FOOTER = [
  ['Products', [['Things for Mac','mac/'],['Things for iPhone','iphone/'],['Things for Watch','watch/'],['Things for iPad','ipad/'],['Things for Vision','vision/']]],
  ['Support', [['Help','support/'],['Contact','contact/'],['Getting Productive','guide/']]],
  ['News', [['Blog','blog/'],['Newsletter','newsletter/'],['Status Board','status/'],['Bluesky','follow/bluesky/'],['X','follow/x/'],['Threads','follow/threads/'],['Instagram','follow/instagram/'],['Mastodon','follow/mastodon/']]],
  ['Company', [['About Us','about/'],['Jobs','jobs/'],['Privacy Policy','privacy/'],['Terms','terms/'],['Press','press/']]],
];
export function layout(page, body) {
  const nav = [['Features','features/'],['Support','support/'],['Blog','blog/']];
  return `<!doctype html><html lang="${page.lang ?? 'ko'}" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escape(page.description ?? 'Things 구조를 참고한 정적 사이트 검토용 예시')} "><meta name="robots" content="noindex,nofollow">${page.layout === 'redirect' ? `<meta http-equiv="refresh" content="0;url=${escape(page.target)}">` : ''}<title>${escape(page.title)} · Things Preview</title><link rel="stylesheet" href="/things/theme/theme.css?v=${THEME_VERSION}"><link rel="stylesheet" href="/things/theme/styles.css?v=${THEME_VERSION}"><script type="module" src="/things/site.js?v=${SCRIPT_VERSION}"></script></head><body data-page="${page.layout}"${['home','contact','newsletter'].includes(page.layout) ? ' class="app-canvas"' : ''}><a class="app-skip" href="#main">본문으로 이동</a><div class="app-shell"><header class="app-header"><a class="app-logo" href="/things/" aria-label="Things"><span class="app-sr">Things</span></a><nav class="app-nav" aria-label="Main navigation">${nav.map(([label,path]) => `<a href="/things/${path}"${page.route.startsWith('/things/'+path) ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav></header></div>${body}<footer class="app-footer"><div class="app-shell"><div class="app-footer-grid">${FOOTER.map(([title,links]) => `<section><h3>${title}</h3><ul>${links.filter(([,path]) => !path.startsWith('follow/')).map(([label,path]) => `<li><a href="/things/${path}">${label}</a></li>`).join('')}${links.some(([,path]) => path.startsWith('follow/')) ? `<li class="app-footer-social">${links.filter(([,path]) => path.startsWith('follow/')).map(([label,path]) => `<a href="/things/${path}" aria-label="${label}"><svg class="app-social-icon" aria-hidden="true"><use href="/things/assets/symbols-social.svg#${path.split('/')[1]}"></use></svg></a>`).join(' ')}</li>` : ''}</ul></section>`).join('')}</div><div class="app-footer-note"><span class="app-sr">화면·동작 검토용 사이트. 본문과 평가는 작성 예시입니다.</span><a href="/things/" aria-label="Cultured Code">${image('footer-company-light.svg','Cultured Code')}</a></div></div></footer></body></html>`;
}
export function article(page, html, headings) {
  const toc = headings.filter((heading) => heading.level === 2);
  return `<div class="app-support-shell"><div class="app-shell">${search()}<main id="main" class="app-body app-article"><h1 class="app-article-title">${page.icon === false ? '' : icon(page.icon)}${escape(page.title)}</h1>${page.description ? `<p class="app-article-lead">${escape(page.description)}</p>` : ''}${page.toc && toc.length ? `<nav class="app-toc" aria-label="In this article"><strong>In this article</strong><ul>${toc.map((heading) => `<li><a href="#${heading.id}">${escape(heading.title)}</a></li>`).join('')}</ul></nav>` : ''}<article class="app-prose">${html}</article><div class="app-contact-prompt"><p>Didn’t find what you were looking for?</p><a href="/things/contact/form/">Contact Us</a></div>${page.syntax ? `<p class="app-caption"><a href="/things/sources/${page.id}.md" download>Markdown 원문</a></p>` : ''}</main></div></div>`;
}
export function blogPost(page, html, linked = false) {
  return `<article class="app-blog-post"><header class="app-post-header"><time class="app-post-date" datetime="${escape(page.date)}">${new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(page.date))}</time><h${linked ? '2' : '1'} class="app-post-title">${linked ? `<a href="${page.route}">` : ''}${escape(page.title)}${linked ? '</a>' : ''}</h${linked ? '2' : '1'}></header><div class="app-prose"><p class="app-article-lead">${escape(page.description)}</p>${html}</div><p class="app-caption">예시 작성자 · <a href="/things/sources/${page.id}.md" download>Markdown 원문</a></p></article>`;
}
export { home, products } from './home.mjs';
