// 본문과 메뉴, 검색, 공통 제품 소개 영역을 조합한다.
import { escape, image, icon } from './markdown.mjs';
export function search(frequent = false) {
  return `<section class="app-search" data-search role="search" aria-label="Support search"><div class="app-search-field">${image('quickfind-loupe.svg', '', 'app-search-icon')}<label class="app-sr" for="article-search">Search support articles</label><input class="app-search-input" id="article-search" type="search" placeholder="Type…" autocomplete="off"><button class="app-search-clear" data-clear type="button" aria-label="Clear search" hidden>${image('quickfind-clear.svg')}</button></div>${frequent ? '<div class="app-search-frequent">Frequent questions: <button data-query="ai tools">ai tools</button> <button data-query="new device">new device</button> <button data-query="discounts">discounts</button> <button data-query="android">android</button></div>' : ''}<div class="app-search-results" data-results role="status" aria-live="polite" hidden></div></section>`;
}
const FOOTER = [
  ['Products', [['Things for Mac','mac/'],['Things for iPhone','iphone/'],['Things for Watch','watch/'],['Things for iPad','ipad/'],['Things for Vision','vision/']]],
  ['Support', [['Help','support/'],['Contact','contact/'],['Getting Productive','guide/'],['문법 전체 보기','support/articles/4651820/']]],
  ['News', [['Blog','blog/'],['Newsletter','newsletter/'],['Status Board','status/'],['Bluesky','follow/bluesky/'],['X','follow/x/'],['Threads','follow/threads/'],['Instagram','follow/instagram/'],['Mastodon','follow/mastodon/']]],
  ['Company', [['About Us','about/'],['Jobs','jobs/'],['Privacy Policy','privacy/'],['Terms','terms/'],['Press','press/']]],
];
export function layout(page, body) {
  const nav = [['Features','features/'],['Support','support/'],['Blog','blog/']];
  return `<!doctype html><html lang="${page.lang ?? 'ko'}" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${escape(page.description ?? 'Things 구조를 참고한 정적 사이트 검토용 예시')} "><meta name="robots" content="noindex,nofollow"><title>${escape(page.title)} · Things Preview</title><link rel="stylesheet" href="/things/theme/theme.css"><link rel="stylesheet" href="/things/theme/styles.css"><script type="module" src="/things/site.js"></script></head><body${page.layout === 'home' ? ' class="app-canvas"' : ''}><a class="app-skip" href="#main">본문으로 이동</a><div class="app-shell"><header class="app-header"><a class="app-logo" href="/things/" aria-label="Things"><span class="app-sr">Things</span></a><nav class="app-nav" aria-label="Main navigation">${nav.map(([label,path]) => `<a href="/things/${path}"${page.route.startsWith('/things/'+path) ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav></header></div>${body}<footer class="app-footer"><div class="app-shell"><div class="app-footer-grid">${FOOTER.map(([title,links]) => `<section><h3>${title}</h3><ul>${links.map(([label,path]) => `<li><a href="/things/${path}">${path.startsWith('follow/') ? `<img class="app-social-icon" src="/things/assets/symbols-social.svg#${path.split('/')[1]}" alt="">` : ''}${label}</a></li>`).join('')}</ul></section>`).join('')}</div><div class="app-footer-note">화면·동작 검토용 사이트 · 본문과 평가는 작성 예시입니다. <a href="/things/support/articles/4651820/">Markdown 작성 문법</a><p>${image('footer-company-light.svg','Cultured Code')}</p></div></div></footer></body></html>`;
}
export function article(page, html, headings) {
  const toc = headings.filter((heading) => heading.level === 2);
  return `<div class="app-shell">${search()}<main id="main" class="app-body app-article"><h1 class="app-article-title">${icon(page.icon)}${escape(page.title)}</h1><p class="app-article-lead">${escape(page.description)}</p>${toc.length ? `<nav class="app-toc" aria-label="In this article"><strong>In this article</strong><ul>${toc.map((heading) => `<li><a href="#${heading.id}">${escape(heading.title)}</a></li>`).join('')}</ul></nav>` : ''}<article class="app-prose">${html}</article><hr><p class="app-caption">예시 문서 · <a href="/things/sources/${page.id}.md" download>Markdown 원문</a> · <a href="/things/support/">All support articles</a></p></main></div>`;
}
export function blogPost(page, html, linked = false) {
  return `<article class="app-blog-post"><time class="app-post-date" datetime="${escape(page.date)}">${escape(page.date)}</time><h${linked ? '2' : '1'} class="app-post-title">${linked ? `<a href="${page.route}">` : ''}${escape(page.title)}${linked ? '</a>' : ''}</h${linked ? '2' : '1'}><div class="app-prose"><p class="app-article-lead">${escape(page.description)}</p>${html}</div><p class="app-caption">예시 작성자 · <a href="/things/sources/${page.id}.md" download>Markdown 원문</a></p></article>`;
}
export function products() {
  return `<section class="app-section"><div class="app-shell">${image('fancysection-icon-download-io70.png','', 'app-section-icon')}<h2 class="app-section-title">Get Things, Get Done</h2><p class="app-intro">각 기기에서 이어지는 경험을 살펴보세요.<br>플랫폼별 화면을 연결한 예시입니다.</p><div class="app-products">${[['Mac','mac','productcard-mac.svg','appstore-mac-black.svg'],['iPhone & Watch','iphone','productcard-iphone-watch.svg','appstore-ios-black.svg'],['iPad','ipad','productcard-ipad.svg','appstore-ios-black.svg'],['Vision Pro','vision','productcard-vision.svg','appstore-ios-black.svg']].map(([title,route,src,badge]) => `<article class="app-product">${image(src,title)}<h3>${title}</h3><a href="/things/${route}/">${image(badge,`${title} 자세히 보기`,'app-store')}</a>${route === 'mac' ? '<a href="/things/trial/">Free trial →</a>' : ''}</article>`).join('')}</div>${image('productcard-things-logo-crop-io75.jpg','','app-product-crop')}</div></section>`;
}
export function home(page, html) {
  return `<main id="main"><section class="app-hero"><div class="app-shell"><h1 class="app-sr">Things</h1>${image('hero-logo-things-io90.png','Things','app-hero-logo')}<p class="app-intro">머릿속의 생각을 정리하고, 오늘 할 일을 고르고, 중요한 일에 집중합니다. 작은 계획이 자연스럽게 다음 행동으로 이어집니다.</p><button class="app-play" data-intro-play type="button">${image('remotecontrol-play.svg')}<span>Watch Introduction Video</span></button></div><div class="app-cinema" data-intro-cinema hidden><video controls playsinline preload="none" poster="/things/assets/meettheallnewthings-poster-e.jpg" aria-label="Introduction video"><source src="/things/assets/meettheallnewthings.mp4" type="video/mp4"></video><p role="status"></p></div>${image('meettheallnewthings2-io75.jpg','기기별 작업 목록 화면','app-hero-scene')}</section><section class="app-section"><div class="app-shell">${image('fancysection-icon-design-io70.png','','app-section-icon')}<h2 class="app-section-title">Simply Powerful</h2><p class="app-intro">복잡한 일도 차근차근.<br>필요한 기능은 가까이, 생각할 공간은 넉넉하게.</p><a class="app-section-link" href="/things/features/">Explore all the features →</a>${image('whatsnew-collage-io60.png','제품 화면 모음','app-collage')}</div></section>${products()}<section class="app-section app-canvas"><div class="app-shell"><h2 class="app-section-title">What People<br>Are Saying</h2>${[0,1].map((batch) => `<div class="app-reviews" data-review-page${batch ? ' hidden' : ''}>${Array.from({length:8},(_,i)=> `<article class="app-review">${image('tweetgrid-avatar-default.png','예시 사용자')}<p>${['오늘 해야 할 일을 한눈에 볼 수 있어 계획을 세우기가 편해졌습니다.','작은 작업을 모아 하나의 프로젝트로 정리하는 흐름이 마음에 듭니다.','필요한 순간에 필요한 목록을 찾을 수 있습니다.','화면이 단순해서 기록하는 일에 집중할 수 있었습니다.'][(batch+i)%4]}</p><strong>Example ${batch*8+i+1}</strong><br><small>실제 평가가 아닌 레이아웃 예시</small></article>`).join('')}</div>`).join('')}<button class="app-review-control" data-review-previous hidden>← Previous Posts</button><button class="app-review-control" data-review-next>Next Posts →</button> <span class="app-caption" data-review-status aria-live="polite">1 / 2</span></div></section><section class="app-section"><div class="app-shell"><h2 class="app-section-title">Read All About It</h2><div class="app-quotes">${Array.from({length:6},(_,i)=>`<blockquote class="app-quote"><p>“${['차분한 화면 안에서 다음 행동을 찾을 수 있습니다.','꾸준히 쓰고 싶은 도구에는 명확한 구조가 있습니다.','복잡한 설명 없이도 흐름을 이해할 수 있습니다.'][i%3]}”</p><cite>리뷰 레이아웃 예시 ${i+1}</cite></blockquote>`).join('')}</div></div></section><section class="app-section app-canvas"><div class="app-shell"><h2 class="app-section-title">Things Newsletter</h2><p class="app-intro">새로운 소식을 전달하는 구독 폼 예시입니다.</p>${html}</div></section></main>`;
}
