import assert from 'node:assert/strict';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { browserScripts } from './browser-scripts.mjs';
import { JSDOM } from 'jsdom';
import { createMarkdown } from './markdown.mjs';
import { values } from './vendor/theme/tokens.js';

test('appended_code_and_tabs_initialize_without_duplicate_handlers_on_existing_elements', async () => {
  const md = createMarkdown();
  const dom = new JSDOM('<main></main>', { url: 'https://example.com/blog/', runScripts: 'outside-only' });
  const { window } = dom;
  const writes = [];
  Object.defineProperty(window, 'isSecureContext', { value: true });
  Object.defineProperty(window.navigator, 'clipboard', { value: { writeText: async value => writes.push(value) } });
  window.eval(browserScripts(fileURLToPath(new URL('./', import.meta.url))).get('document.js'));
  const main = window.document.querySelector('main');
  main.innerHTML = md.render('```js\nconst appended = true;\n```\n\n:::tabs\n@tab 첫째\n하나\n@tab 둘째\n둘\n:::end');
  main.querySelector('.app-code').style.setProperty('--duration-notice', `${values.duration.notice}ms`);
  for (let i = 0; i < 2; i++) window.document.dispatchEvent(new window.CustomEvent('content-added', { detail: main }));
  const copy = main.querySelector('[data-tool="copy"]');
  assert.equal(copy.hidden, false);
  copy.click();
  await new Promise(resolve => setImmediate(resolve));
  assert.deepEqual(writes, ['const appended = true;\n']);
  const buttons = main.querySelectorAll('[role=tab]');
  buttons[1].click();
  assert.equal(buttons[1].getAttribute('aria-selected'), 'true');
  assert.equal(main.querySelectorAll('[role=tabpanel]')[0].hidden, true);
  dom.window.close();
});
